#!/usr/bin/env python3
"""Validate xenia-wire's repository-conformance and claims contracts."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]
ROOT_RESOLVED = ROOT.resolve()

ALLOWED_MATURITY = {
    "experimental",
    "research",
    "pre-alpha",
    "alpha",
    "beta",
    "stable",
    "archived",
}
ALLOWED_COVERAGE = {"partial", "complete"}
ALLOWED_LEVELS = {"RC-0", "RC-1", "RC-2", "RC-3"}
ALLOWED_KINDS = {"maturity", "protocol", "conformance", "capability", "non_claim"}
ALLOWED_STATUSES = {"current", "declared_boundary", "published_fixture", "implemented_internal"}
CLAIM_ID_RE = re.compile(r"^[A-Z0-9][A-Z0-9-]+$")
SCOPE_RE = re.compile(r"^[a-z0-9][a-z0-9-]+$")


class ContractError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ContractError(message)


def _within_root(path: Path) -> bool:
    return path == ROOT_RESOLVED or ROOT_RESOLVED in path.parents


def safe_repo_path(raw: str, context: str, *, must_exist: bool = True) -> Path:
    """Resolve a repository-relative path without allowing traversal/symlink escape."""
    require(isinstance(raw, str) and raw.strip(), f"{context} must be a non-empty path")
    path = Path(raw)
    require(not path.is_absolute(), f"{context} must be repository-relative")
    require(".." not in path.parts, f"{context} must not escape the repository")

    candidate = ROOT / path
    try:
        parent = candidate.parent.resolve(strict=True)
    except OSError as exc:
        raise ContractError(f"{context} parent cannot be resolved: {raw}: {exc}") from exc
    require(_within_root(parent), f"{context} escapes repository through parent/symlink: {raw}")

    if candidate.exists():
        try:
            resolved = candidate.resolve(strict=True)
        except OSError as exc:
            raise ContractError(f"{context} cannot be resolved: {raw}: {exc}") from exc
        require(_within_root(resolved), f"{context} escapes repository through symlink: {raw}")
    elif must_exist:
        raise ContractError(f"{context} does not exist: {raw}")

    return candidate


def load_toml(path: Path) -> dict:
    try:
        return tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        try:
            display = path.relative_to(ROOT)
        except ValueError:
            display = path
        raise ContractError(f"{display}: {exc}") from exc


def require_bool(mapping: dict, key: str, context: str) -> None:
    require(type(mapping.get(key)) is bool, f"{context}.{key} must be a boolean")


def render_claims(claims_doc: dict) -> str:
    lines = [
        "# Registered Claims",
        "",
        "<!-- generated by scripts/check-repo-integrity.py; do not hand-edit -->",
        "",
        f"Registry coverage: **{claims_doc['coverage']}**.",
        "",
        "This file is a deterministic rendering of `claims.toml`. The registry is authoritative only for claims that have been migrated into it.",
        "",
        "| ID | Scope | Kind | Status | Statement | Evidence | Limitations |",
        "|---|---|---|---|---|---|---|",
    ]

    def cell(value: str) -> str:
        return value.replace("|", r"\|").replace("\n", " ")

    for claim in claims_doc["claim"]:
        evidence = "<br>".join(f"`{cell(path)}`" for path in claim["evidence"])
        limitations = "<br>".join(cell(item) for item in claim["limitations"])
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{cell(claim['id'])}`",
                    f"`{cell(claim['scope'])}`",
                    cell(claim["kind"]),
                    cell(claim["status"]),
                    cell(claim["statement"]),
                    evidence,
                    limitations,
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Status semantics",
            "",
            "- `scope` states which repository/protocol/component surface the claim is about; evidence for one scope does not silently promote another.",
            "- `declared_boundary` records a current maturity/non-claim boundary; it is not a positive security result.",
            "- `current` records a current repository statement whose evidence path is present; it does not imply external validation.",
            "- `published_fixture` records committed conformance data; fixture presence is not full protocol qualification.",
            "- `implemented_internal` records an implementation or checker maintained inside this repository/organization; it is not external replication or audit.",
            "",
        ]
    )
    return "\n".join(lines)


def validate_package_readme_parity() -> None:
    """Keep the README's concrete install example bound to Cargo package metadata."""
    cargo_path = safe_repo_path("Cargo.toml", "package metadata")
    cargo = load_toml(cargo_path)
    package = cargo.get("package")
    require(isinstance(package, dict), "Cargo.toml [package] table is required")

    package_name = package.get("name")
    version = package.get("version")
    require(package_name == "xenia-wire", "unexpected Cargo package name")
    require(isinstance(version, str) and version.strip(), "Cargo package version is required")

    readme = safe_repo_path("README.md", "README package surface").read_text(encoding="utf-8")
    install_literal = f"cargo add '{package_name}@{version}'"
    current_version_literal = f"currently `{version}`"
    require(
        install_literal in readme,
        f"README install command is stale; expected exact package version {version}",
    )
    require(
        current_version_literal in readme,
        f"README current-version prose is stale; expected {version}",
    )


def validate() -> tuple[dict, dict]:
    repo = load_toml(ROOT / "repo.toml")

    require(repo.get("schema_version") == 1, "repo.toml schema_version must be 1")
    require(repo.get("repository") == "Luminous-Dynamics/xenia-wire", "unexpected repository identity")

    claims_path = safe_repo_path(repo.get("claims_manifest", "claims.toml"), "repo.toml.claims_manifest")
    claims = load_toml(claims_path)
    require(claims.get("schema_version") == 1, "claims.toml schema_version must be 1")

    ci_repository = os.environ.get("GITHUB_REPOSITORY")
    if ci_repository:
        require(repo["repository"] == ci_repository, "repo.toml repository does not match GITHUB_REPOSITORY")

    require(repo.get("maturity") in ALLOWED_MATURITY, "repo.toml maturity is not recognized")
    require(repo.get("conformance_level") in ALLOWED_LEVELS, "repo.toml conformance_level is invalid")
    require_bool(repo, "canonical", "repo.toml")
    require_bool(repo, "production_ready", "repo.toml")
    require_bool(repo, "external_security_audit", "repo.toml")

    require(repo.get("claims_coverage") in ALLOWED_COVERAGE, "repo.toml claims_coverage is invalid")
    require(claims.get("coverage") in ALLOWED_COVERAGE, "claims.toml coverage is invalid")
    require(repo["claims_coverage"] == claims["coverage"], "repo.toml and claims.toml coverage disagree")

    require(claims.get("generated_document") == repo.get("claims_render"), "claims render paths disagree")
    safe_repo_path(repo["claims_render"], "repo.toml.claims_render", must_exist=False)
    status_path = safe_repo_path(repo["status_document"], "repo.toml.status_document")

    policy = repo.get("policy")
    require(isinstance(policy, dict), "repo.toml.policy must be a table")
    policy_keys = (
        "require_claim_scope",
        "require_claim_evidence_paths",
        "require_claim_limitations",
        "require_status_claims_pointer",
        "require_repo_path_containment",
        "require_checker_adversarial_tests",
        "require_exact_source_qualification",
        "require_protected_promotion",
    )
    for key in policy_keys:
        require_bool(policy, key, "repo.toml.policy")

    if repo["conformance_level"] in {"RC-1", "RC-2", "RC-3"}:
        require(policy["require_claim_scope"], "RC-1+ requires explicit claim scope")
        require(policy["require_claim_evidence_paths"], "RC-1+ requires evidence-path checks")
        require(policy["require_claim_limitations"], "RC-1+ requires claim limitations")
        require(policy["require_repo_path_containment"], "RC-1+ requires repository path containment")
        require(policy["require_checker_adversarial_tests"], "RC-1+ requires checker adversarial tests")
        safe_repo_path("scripts/test-repo-integrity.py", "RC-1 checker tests")

    promotion = repo.get("promotion")
    require(isinstance(promotion, dict), "repo.toml.promotion must be a table")
    require(
        isinstance(promotion.get("canonical_branch"), str) and promotion["canonical_branch"].strip(),
        "promotion.canonical_branch is required",
    )
    require_bool(promotion, "protected", "repo.toml.promotion")
    require(isinstance(promotion.get("required_checks"), list), "promotion.required_checks must be a list")
    if repo["conformance_level"] == "RC-3":
        require(promotion["protected"], "RC-3 requires a protected canonical promotion boundary")
        require(policy["require_protected_promotion"], "RC-3 requires protected-promotion policy")

    claim_list = claims.get("claim")
    require(isinstance(claim_list, list) and claim_list, "claims.toml must contain at least one [[claim]]")

    seen_ids: set[str] = set()
    for index, claim in enumerate(claim_list):
        context = f"claims.toml.claim[{index}]"
        require(isinstance(claim, dict), f"{context} must be a table")

        claim_id = claim.get("id")
        require(isinstance(claim_id, str) and claim_id.strip(), f"{context}.id is required")
        require(CLAIM_ID_RE.fullmatch(claim_id) is not None, f"{claim_id}: invalid stable claim id")
        require(claim_id not in seen_ids, f"duplicate claim id: {claim_id}")
        seen_ids.add(claim_id)

        scope = claim.get("scope")
        require(isinstance(scope, str) and scope.strip(), f"{claim_id}: scope is required")
        require(SCOPE_RE.fullmatch(scope) is not None, f"{claim_id}: invalid scope slug")

        require(claim.get("kind") in ALLOWED_KINDS, f"{claim_id}: unsupported kind")
        require(claim.get("status") in ALLOWED_STATUSES, f"{claim_id}: unsupported status")
        require(
            isinstance(claim.get("statement"), str) and claim["statement"].strip(),
            f"{claim_id}: statement is required",
        )

        evidence = claim.get("evidence")
        require(isinstance(evidence, list) and evidence, f"{claim_id}: evidence must be non-empty")
        require(len(evidence) == len(set(evidence)), f"{claim_id}: duplicate evidence path")
        for evidence_index, raw_path in enumerate(evidence):
            safe_repo_path(raw_path, f"{claim_id}.evidence[{evidence_index}]")

        limitations = claim.get("limitations")
        require(
            isinstance(limitations, list)
            and limitations
            and all(isinstance(item, str) and item.strip() for item in limitations),
            f"{claim_id}: limitations must contain at least one non-empty string",
        )

    status_text = status_path.read_text(encoding="utf-8")
    if policy["require_status_claims_pointer"]:
        require(
            "<!-- repo-status: claims.toml -->" in status_text,
            "status document must explicitly point to claims.toml",
        )

    validate_package_readme_parity()
    return repo, claims


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="validate and require generated docs to match")
    mode.add_argument("--write", action="store_true", help="validate and rewrite generated docs")
    args = parser.parse_args()

    try:
        repo, claims = validate()
        rendered = render_claims(claims)
        rendered_path = safe_repo_path(
            repo["claims_render"],
            "repo.toml.claims_render",
            must_exist=not args.write,
        )

        if args.write:
            rendered_path.write_text(rendered, encoding="utf-8")
        else:
            actual = rendered_path.read_text(encoding="utf-8")
            require(
                actual == rendered,
                f"{repo['claims_render']} is stale; run scripts/check-repo-integrity.py --write",
            )
    except ContractError as exc:
        print(f"repo-integrity: FAIL: {exc}", file=sys.stderr)
        return 1

    print("repo-integrity: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
